"""Generate a synthetic demo (stereo wav + label json) for trying the CLI.

This is NOT a throwaway: it produces a config-valid sample so a fresh checkout
can be exercised end-to-end without any private game recordings.

Usage:
    python scripts/make_demo_sample.py            # writes to ./_demo/
    python scripts/make_demo_sample.py --out /tmp/demo
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import soundfile as sf


def make_stereo_wav(path: Path, *, sample_rate: int = 48000, duration_s: float = 1.0) -> None:
    """Write a short stereo tone with a slight inter-channel delay (fake ITD)."""
    n = int(sample_rate * duration_s)
    t = np.arange(n) / sample_rate
    left = 0.2 * np.sin(2 * np.pi * 440.0 * t)
    # Delay the right channel a few samples so the two channels differ.
    delay = 8
    right = np.zeros_like(left)
    right[delay:] = 0.2 * np.sin(2 * np.pi * 440.0 * t[:-delay])
    stereo = np.stack([left, right], axis=1).astype("float32")
    path.parent.mkdir(parents=True, exist_ok=True)
    sf.write(str(path), stereo, sample_rate, subtype="PCM_16")


def make_label(path: Path) -> None:
    label = {
        "schema_version": "1.1",
        "map_id": "de_dust2",
        "capture_origin": "research",
        "listener": {
            "position": {"x": 0.0, "y": 0.0, "z": 64.0},
            "yaw": 90.0,
            "pitch": 0.0,
            "roll": 0.0,
        },
        "source": {
            "position": {"x": 600.0, "y": 300.0, "z": 64.0},
            "sound_type": "footstep_run",
            "source_id": "demo_enemy",
        },
        "weapon": None,
        "game_build": "demo",
        "notes": "Synthetic demo sample generated by scripts/make_demo_sample.py",
        # Optional training-oriented fields (recommended in real captures).
        "listener_point_id": "demo_listener",
        "source_point_id": "demo_source",
        "action": "footstep_run",
        "material": "concrete",
        "floor_relation": "same",
        "distance_m": 6.7,
        "occlusion": "none",
        "area_id": "demo_area",
        "extra": {"synthetic": True},
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(label, indent=2), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a demo audio+label pair.")
    parser.add_argument("--out", type=Path, default=Path("_demo"))
    args = parser.parse_args()

    audio_path = args.out / "demo_sample.wav"
    label_path = args.out / "demo_sample.json"
    make_stereo_wav(audio_path)
    make_label(label_path)

    print(f"Wrote: {audio_path}")
    print(f"Wrote: {label_path}")
    print("\nNow import it with:")
    print(f"  python -m apps.cli import-sample --audio {audio_path} --label {label_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
